// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID          int64          `json:"id"`
	EntryID     sql.NullInt64  `json:"entry_id"`
	UserID      sql.NullString `json:"user_id"`
	Content     sql.NullString `json:"content"`
	CommentedOn time.Time      `json:"commented_on"`
}

type Connection struct {
	PartyA        string    `json:"party_a"`
	PartyB        string    `json:"party_b"`
	ConnectedDate time.Time `json:"connected_date"`
}

type Medium struct {
	ID      int64          `json:"id"`
	EntryID sql.NullInt64  `json:"entry_id"`
	Url     sql.NullString `json:"url"`
}

type TravelEntry struct {
	ID          int64          `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	TripID      sql.NullInt64  `json:"trip_id"`
	Location    sql.NullString `json:"location"`
	Description sql.NullString `json:"description"`
}

type Trip struct {
	ID        int64          `json:"id"`
	Title     sql.NullString `json:"title"`
	Country   sql.NullString `json:"country"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
}

type User struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	ProfilePicture sql.NullString `json:"profile_picture"`
	CreationDate   time.Time      `json:"creation_date"`
}

type UserTrip struct {
	TripID int64  `json:"trip_id"`
	UserID string `json:"user_id"`
}
